data:
  - id: ClodQiu
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ClodQiu/STARS/master/list.yml
    output: subs/ClodQiu.yaml
  - id: Pawdroid
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
    output: subs/Pawdroid.yaml
  - id: a2470982985
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/a2470982985/getNode/main/clash.yaml
    output: subs/a2470982985.yaml
  - id: abshare
    source: v2ray
    target: clash
    urls:
      - https://utils.2424014450.workers.dev/markdown?target=https%3A%2F%2Fraw.githubusercontent.com%2Fabshare%2Fabshare.github.io%2Fmain%2FREADME.md
    output: subs/abshare.yaml
  - id: aiboboxx
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
    output: subs/aiboboxx.yaml
  - id: chengaopan
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
    output: subs/chengaopan.yaml
  - id: edgetunnel
    source: clash
    target: clash
    urls:
      - https://edgetunnel.2424014450.workers.dev/113dd109-540e-4497-9d47-eed30315260f
    headers: { 'User-Agent': 'clash' }
    output: subs/edgetunnel.yaml
  - id: ermaozi
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
    output: subs/ermaozi.yaml
  - id: freefq
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/freefq/free/master/v2
    output: subs/freefq.yaml
  - id: mfuu
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
    output: subs/mfuu.yaml
  - id: ChromeGo
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/1/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/2/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/3/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/13/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/15/config.yaml
    output: subs/ChromeGo.yaml
  - id: mksshare
    source: v2ray
    target: clash
    urls:
      - https://utils.2424014450.workers.dev/markdown?target=https%3A%2F%2Fraw.githubusercontent.com%2Fmksshare%2Fmksshare.github.io%2Fmain%2FREADME.md
    output: subs/mksshare.yaml
  - id: peasoft
    source: v2ray
    target: clash
    urls:
      - https://utils.2424014450.workers.dev?target=https%3A%2F%2Fraw.githubusercontent.com%2Fpeasoft%2FNoMoreWalls%2Fmaster%2Flist_raw.txt
    output: subs/peasoft.yaml
  - id: shunfeng
    source: clash
    target: clash
    urls:
      - https://shunfeng.2424014450.workers.dev
    output: subs/shunfeng.yaml
  - id: tolinkshare
    source: clash
    target: clash
    urls:
      - https://utils.2424014450.workers.dev/markdown?target=https%3A%2F%2Fraw.githubusercontent.com%2Ftolinkshare%2Ffreenode%2Fmain%2FREADME.md
    output: subs/tolinkshare.yaml
  - id: w1770946466
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription_num
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription1
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription2
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription3
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription4
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription5
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription6
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription7
      - https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription8
    output: subs/w1770946466.yaml
  - id: xrayvip
    source: clash
    target: clash
    urls:
      - https://www.xrayvip.com/free.yaml
    output: subs/xrayvip.yaml
  - id: zhangkaiitugithub
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
    output: subs/zhangkaiitugithub.yaml
