data:
  - id: ClodQiu
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ClodQiu/STARS/master/list.yml
    output: subs/ClodQiu.yaml
  - id: Pawdroid
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
    output: subs/Pawdroid.yaml
  - id: a2470982985
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/a2470982985/getNode/main/clash.yaml
    output: subs/a2470982985.yaml
  - id: abshare
    source: v2ray
    target: clash
    urls:
      - https://utils.2424014450.workers.dev/markdown?target=https%3A%2F%2Fraw.githubusercontent.com%2Fabshare%2Fabshare.github.io%2Fmain%2FREADME.md
    output: subs/abshare.yaml
  - id: aiboboxx
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
    output: subs/aiboboxx.yaml
  - id: chengaopan
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
    output: subs/chengaopan.yaml
  - id: edgetunnel
    source: clash
    target: clash
    urls:
      - https://edgetunnel.2424014450.workers.dev/113dd109-540e-4497-9d47-eed30315260f
    headers: { 'User-Agent': 'clash' }
    output: subs/edgetunnel.yaml
  - id: ermaozi
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
    output: subs/ermaozi.yaml
  - id: freefq
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/freefq/free/master/v2
    output: subs/freefq.yaml
  - id: mfuu
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
    output: subs/mfuu.yaml
  - id: ChromeGo
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/1/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/2/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/3/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/13/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/15/config.yaml
    output: subs/ChromeGo.yaml
  - id: mksshare
    source: v2ray
    target: clash
    urls:
      - https://utils.2424014450.workers.dev/markdown?target=https%3A%2F%2Fraw.githubusercontent.com%2Fmksshare%2Fmksshare.github.io%2Fmain%2FREADME.md
    output: subs/mksshare.yaml
  - id: peasoft
    source: v2ray
    target: clash
    urls:
      - https://utils.2424014450.workers.dev?target=https%3A%2F%2Fraw.githubusercontent.com%2Fpeasoft%2FNoMoreWalls%2Fmaster%2Flist_raw.txt
    output: subs/peasoft.yaml
  - id: shunfeng
    source: clash
    target: clash
    urls:
      - https://shunfeng.2424014450.workers.dev
    output: subs/shunfeng.yaml
  - id: tolinkshare
    source: clash
    target: clash
    urls:
      - https://utils.2424014450.workers.dev/markdown?target=https%3A%2F%2Fraw.githubusercontent.com%2Ftolinkshare%2Ffreenode%2Fmain%2FREADME.md
    output: subs/tolinkshare.yaml
  - id: xrayvip
    source: clash
    target: clash
    urls:
      - https://www.xrayvip.com/free.yaml
    output: subs/xrayvip.yaml
  - id: zhangkaiitugithub
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
    output: subs/zhangkaiitugithub.yaml
  - id: ripaojiedian
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
    output: subs/ripaojiedian.yaml
  - id: yaney01
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/yaney01/Yaney01/main/temporary
    output: subs/yaney01.yaml
  - id: hkaa0
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/V2ray
    output: subs/hkaa0.yaml
  - id: soroushmirzaei
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/ws
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/ws
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/ws
    output: subs/soroushmirzaei.yaml
  - id: mheidari98
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/mheidari98/.proxy/main/all
    output: subs/mheidari98.yaml
  - id: mahdibland
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml
      - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/EternityAir.yml
    output: subs/mahdibland.yaml