data:
  - id: ClodQiu
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ClodQiu/STARS/master/list.yml
    output: subs/ClodQiu.yaml
  - id: Pawdroid
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fgithub.com%2FPawdroid%2FFree-servers%2Fraw%2Fmain%2Fsub&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/Pawdroid.yaml
  - id: a2470982985
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/a2470982985/getNode/main/clash.yaml
    output: subs/a2470982985.yaml
  - id: abshare
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Futils.2424014450.workers.dev%2Fmarkdown%3Ftarget%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Fabshare%252Fabshare.github.io%252Fmain%252FREADME.md&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/abshare.yaml
  - id: aiboboxx
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Fmain%2Fv2&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/aiboboxx.yaml
  - id: chengaopan
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
    output: subs/chengaopan.yaml
  - id: edgetunnel
    source: clash
    target: clash
    urls:
      - https://edgetunnel.2424014450.workers.dev/113dd109-540e-4497-9d47-eed30315260f
    headers: { 'User-Agent': 'clash' }
    output: subs/edgetunnel.yaml
  - id: ermaozi
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
    output: subs/ermaozi.yaml
  - id: freefq
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Ffreefq%2Ffree%2Fmaster%2Fv2&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/freefq.yaml
  - id: mfuu
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
    output: subs/mfuu.yaml
  - id: ChromeGo
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/1/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/2/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/3/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/13/config.yaml
      - https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/15/config.yaml
    output: subs/ChromeGo.yaml
  - id: mksshare
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Futils.2424014450.workers.dev%2Fmarkdown%3Ftarget%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Fmksshare%252Fmksshare.github.io%252Fmain%252FREADME.md&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/mksshare.yaml
  - id: peasoft
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Futils.2424014450.workers.dev%3Ftarget%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Fpeasoft%252FNoMoreWalls%252Fmaster%252Flist_raw.txt&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/peasoft.yaml
  - id: shunfeng
    source: clash
    target: clash
    urls:
      - https://shunfeng.2424014450.workers.dev
    output: subs/shunfeng.yaml
  - id: tolinkshare
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Futils.2424014450.workers.dev%2Fmarkdown%3Ftarget%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Ftolinkshare%252Ffreenode%252Fmain%252FREADME.md&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/tolinkshare.yaml
  - id: w1770946466
    source: clash
    target: clash
    urls:
      - https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription1%7Chttps%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription2%7Chttps%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription3%7Chttps%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription4%7Chttps%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription5%7Chttps%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription6%7Chttps%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription7%7Chttps%3A%2F%2Fraw.githubusercontent.com%2Fw1770946466%2FAuto_proxy%2Fmain%2FLong_term_subscription8&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    output: subs/w1770946466.yaml
  - id: xrayvip
    source: clash
    target: clash
    urls:
      - https://www.xrayvip.com/free.yaml
    output: subs/xrayvip.yaml
  - id: zhangkaiitugithub
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
    output: subs/zhangkaiitugithub.yaml
