name: Cloudflare Ip Test

on:
  # workflow文件变动时触发
  push:
    paths:
      - '.github/workflows/cloudflare_ip_test.yml'
  # 定时触发
  schedule:
    - cron: '0 */1 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  cloudfalre_ip_test:
    runs-on: [self-hosted, windows, x64]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Ip Test
        run: |
          cd .\tools
          powershell -command "Expand-Archive .\CloudflareST.zip .\CloudflareST" 
          cd .\CloudflareST
          .\test.bat

      - name: Upload Result
        run: |
          cd .\tools
          if exist ".\CloudflareST\cloudflare_official.txt" (.\gfp.exe -r https://github.com/${{ github.repository }} -f ips/cloudflare_official.txt -l .\CloudflareST\cloudflare_official.txt -t ${{ secrets.GITHUB_TOKEN }})
          if exist ".\CloudflareST\cloudflare_reverse.txt" (.\gfp.exe -r https://github.com/${{ github.repository }} -f ips/cloudflare_reverse.txt -l .\CloudflareST\cloudflare_reverse.txt -t ${{ secrets.GITHUB_TOKEN }})
          
          

