name: Auto-fetch Preferred IP

on:
  # 定时触发
  schedule:
    - cron: '0 */1 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  cloudfalre_ip_test:
    runs-on: self-hosted
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Test
        run: .\tools\CloudflareST\CloudflareST.exe -n 200 -t 10 -dn 50 -tl 200 -sl 5 -p 0 -f ip.txt -o result.csv

      - name: Upload
        run: .\tools\gfp.exe -r https://github.com/${{ github.repository }} -f ips/cf.txt -l .\tools\CloudflareST\ip.txt -t ${{ secrets.GITHUB_TOKEN }}


