name: Auto-fetch Preferred IP

on:
  # 定时触发
  schedule:
    - cron: '0 */1 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  cloudfalre_ip_test:
    runs-on: self-hosted
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd .\tools\CloudflareST
          .\test.bat

      - name: Upload
        run: |
          cd .\tools
          .\gfp.exe -r https://github.com/${{ github.repository }} -f ips/cloudflare_official.txt -l .\CloudflareST\cloudflare_official.txt -t ${{ secrets.GITHUB_TOKEN }}



