name: Auto pull 

on:
  push:
    branches:
      - main

jobs:
  download-and-add-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup environment
        run: |
          declare -A files=(
            ["tolinkshare.yaml"]="https://sub.xeton.dev/sub?target=clash&new_name=true&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&url=https%3A%2F%2Fmarkdown.2424014450.workers.dev%2F%3Ftarget%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Ftolinkshare%2Ffreenode%2Fmain%2FREADME.md"
            ["mksshare.yaml"]="https://sub.xeton.dev/sub?target=clash&new_name=true&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&url=https%3A%2F%2Fmarkdown.2424014450.workers.dev%2F%3Ftarget%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Fmksshare%2Fmksshare.github.io%2Fmain%2FREADME.md"
          )

      - name: Download files
        run: |
          for file_name in "${!files[@]}"; do
            curl -o ${file_name} -L ${files[$file_name]}
          done

      - name: Add files to Git
        run: |
          pwd
          cat mksshare.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          for file_name in "${!files[@]}"; do
            git add ${file_name}
          done

      - name: Commit and Push files
        run: |
          git commit -m "Add downloaded files"
          git push