name: Auto pull 

on:
  push:
    branches:
      - main

jobs:
  download-and-add-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download files
        run: |
          pwd
          ls
          curl -L -o ClodQiu.yaml            'https://raw.githubusercontent.com/ClodQiu/STARS/master/list.yml'
          curl -L -o Pawdroid.yaml           'https://sub.xeton.dev/sub?target=clash&new_name=true&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&url=https%3A%2F%2Fgithub.com%2FPawdroid%2FFree-servers%2Fraw%2Fmain%2Fsub'
          curl -L -o a2470982985.yaml        'https://raw.githubusercontent.com/a2470982985/getNode/main/clash.yaml'
          curl -L -o abshare.yaml            'https://sub.xeton.dev/sub?target=clash&new_name=true&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&url=https%3A%2F%2Fmarkdown.2424014450.workers.dev%2F%3Ftarget%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Fabshare%2Fabshare.github.io%2Fmain%2FREADME.md'
          curl -L -o chengaopan.yaml         'https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml'
          curl -L -o mianayang.yaml          'https://raw.githubusercontent.com/mianayang/chromego_merge/main/sub/merged_proxies_new.yaml'
          curl -L -o mksshare.yaml           'https://sub.xeton.dev/sub?target=clash&new_name=true&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&url=https%3A%2F%2Fmarkdown.2424014450.workers.dev%2F%3Ftarget%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Fmksshare%2Fmksshare.github.io%2Fmain%2FREADME.md'
          curl -L -o oneclash.yaml           'https://oneclash.2424014450.workers.dev'
          curl -L -o shunfeng.yaml           'https://shunfeng.2424014450.workers.dev'
          curl -L -o tolinkshare.yaml        'https://sub.xeton.dev/sub?target=clash&new_name=true&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&url=https%3A%2F%2Fmarkdown.2424014450.workers.dev%2F%3Ftarget%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Ftolinkshare%2Ffreenode%2Fmain%2FREADME.md'
          curl -L -o xrayvip.yaml            'https://www.xrayvip.com/free.yaml'
          curl -L -o zhangkaiitugithub.yaml  'https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml'

      - name: Add files to Git
        run: |
          git add subs/ClodQiu.yaml
          git add subs/Pawdroid.yaml
          git add subs/a2470982985.yaml
          git add subs/abshare.yaml
          git add subs/chengaopan.yaml
          git add subs/mianayang.yaml
          git add subs/mksshare.yaml
          git add subs/oneclash.yaml
          git add subs/shunfeng.yaml
          git add subs/tolinkshare.yaml
          git add subs/xrayvip.yaml
          git add subs/zhangkaiitugithub.yaml

      - name: Commit and Push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add downloaded files"
          git push