name: 节点测速

on:
  # fetch执行后触发
  workflow_run:
    workflows: ['拉取订阅文件']
    types:
      - completed
  # 手动触发
  workflow_dispatch:

jobs:
  test-proxies-within:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 测试节点
        run: |
          ~/metaST --config ./subs/merged/merged.yaml --output ./subs/merged/tested_within.yaml --dt 1000 --dr 10 --df 800 --dn 64 --ff 0.2

      - name: 上传测试结果
        run: |
          git subs/merged/tested_within.yaml
          git commit -m "Tested by meataST"
          
