name: Auto-fetch Subscribed Files

on:
  # workflow文件变动时触发
  push:
    paths:
      - '.github/workflows/subcribe_files_fetch.yml'
  # 定时触发
  schedule:
    - cron: '0 */1 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  fetch-subcribe-files:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch subscribe files
        uses: dongchengjie/subs-puller@main
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          config: http://raw.githubusercontent.com/dongchengjie/airport/subs/_config.yaml
