name: 拉取订阅文件

on:
  push:
    paths:
      - '.github/workflows/subcribe_files_fetch.yml'
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  fetch-subcribe-files:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch subscribe files
        uses: dongchengjie/subs-puller@main
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          config: https://raw.githubusercontent.com/dongchengjie/airport/main/subs/_config.yaml
