name: 节点测速

on:
  # fetch执行后触发
  workflow_run:
    workflows: ['拉取订阅文件']
    types:
      - completed
  # 手动触发
  workflow_dispatch:

jobs:
  test-proxies-within:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 下载metaST
        run: |
          curl -s -x 127.0.0.1:7890 -o metaST.zip --retry 5 -L https://github.com/dongchengjie/metaST/releases/latest/download/metaST-linux-amd64.zip
          7za -o./ x metaST.zip && mv ./metaST-linux-amd64 ./metaST && chmod +x ./metaST

      - name: 测试节点
        run: |
          ./metaST --config ~/mihomo/config.yaml --output ./subs/merged/tested_within.yaml --dt 1000 --dr 10 --df 800 --dn 64 --ff 0.2

      - name: 上传测试结果
        run: |
          git config --global user.email "metast@github.com"
          git config --global user.name "metast"
          git add subs/merged/tested_within.yaml
          git commit -m "Tested by meataST"

      - name: 更新本地代理
        run: |
          cp -f ./subs/merged/tested_within.yaml ~/mihomo/config.yaml
          curl -X POST http://127.0.0.1:9090/restart