name: Delete workflow runs on schedule

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Delete workflow runs
        uses: dongchengjie/workflow-runs-cleaner@master
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          maintain-span: '1d'
